Update patch set 35
Patch Set 35:

> Patch Set 35:
> 
> > The automated tests are passing on stable-2.16, but they do not even build on master :-(
> 
> When I run the plugin tests locally on master (gerrit tree), they all built and passed for me. But maybe you are referring to a CI run of those, as opposed to a typical bazel plugin one?

bazel test plugins/its-jira:its_jira_tests fails for me and for the CI also.

plugins/its-jira/src/test/java/com/googlesource/gerrit/plugins/its/jira/JiraITTest.java:260: error: cannot find symbol
        .create(db, admin.getIdent(), testRepo, JIRA_ISSUE, "a.txt", "test")

On Gerrit master, reviewDb is gone and so the 'db' instance variable in the integration tests. Are you sure that the master branch of its-jira + Gerrit master are working locally for you? Have you fetched the latest and greatest of Gerrit without ReviewDb?
 
> > > We are still deploying 2.14 with a corresponding version of this change in.
> > 
> > Yes, I remember that. We could try to see if this merges cleanly on v2.15 also, so that you guys can get rid of the fork as soon as you upgrade to that version. WDYT?
> 
> We will need to revisit our its forks for an upcoming 2.15 deployment, yes. I agree with the idea of aiming for a 2.15 version of this change first then merge-up again. Would not lose the work done in this very master/2.16 change for when the latter unfolds.

Let me try to see if this would work on v2.15 and, if yes, I'll move the change there.
Staying on a fork is always painful, I'd be happy to allow you guys to relief the pain ASAP.

Patch-set: 35
Reviewer: Gerrit User 1006192 <1006192@173816e5-2b9a-37c3-8a2e-48639d4f1153>