Update patch set 35
Patch Set 35:

> bazel test plugins/its-jira:its_jira_tests fails for me and for the CI also.
> 
> plugins/its-jira/src/test/java/com/googlesource/gerrit/plugins/its/jira/JiraITTest.java:260: error: cannot find symbol
>         .create(db, admin.getIdent(), testRepo, JIRA_ISSUE, "a.txt", "test")
> 
> On Gerrit master, reviewDb is gone and so the 'db' instance variable in the integration tests. Are you sure that the master branch of its-jira + Gerrit master are working locally for you? Have you fetched the latest and greatest of Gerrit without ReviewDb?

The LOC you refer to (above) doesn't match the one from this change ([1], below). Also, I think I did update my local setup to the current latest versions; please see [2]:

[1] .create(admin.getIdent(), testRepo, JIRA_ISSUE, "a.txt", "test")
[2] <=>
- its-base 727d100;
- its-jira 869b290, this change, which should be properly based;
- gerrit 1bec79f, latest master when pulled locally earlier today;
- plugins/its-{base|jira} both linked;
- plugins/external_plugin_deps.bzl linked to its-jira's;
- tools/bzl/plugins.bzl modified with both its-{base|jira} in it;
- bazel clean --expunge, done in both its-base and gerrit (its-jira cannot);
- bazel build api && ./tools/maven/api.sh install, because I can be paranoid;
- bazel build plugins/its-{base|jira}, both commands successful;
- bazel test plugins/its-base:its_base_tests and
- bazel test plugins/its-jira:its_jira_tests both successful, too;
- bazel build release, which I used to init a loading default site with both its-{base|jira}.

> > We will need to revisit our its forks for an upcoming 2.15 deployment, yes. I agree with the idea of aiming for a 2.15 version of this change first then merge-up again. Would not lose the work done in this very master/2.16 change for when the latter unfolds.
> 
> Let me try to see if this would work on v2.15 and, if yes, I'll move the change there.
> Staying on a fork is always painful, I'd be happy to allow you guys to relief the pain ASAP.

Indeed; thanks.

Patch-set: 35
Reviewer: Gerrit User 1012732 <1012732@173816e5-2b9a-37c3-8a2e-48639d4f1153>