Update patch set 27
Patch Set 27:

I forgot to update Gerrit submodules on the last attempt.  This time updating submodule and rebuilding the pluign I get this failure..


~/w/gerrit-plugin-cr ❯❯❯ bazel build plugins/its-jira                                     master ✱ ◼
INFO: Found 1 target...
ERROR: /Users/zaro0508/work-gerrit/gerrit-plugin-cr/plugins/its-jira/BUILD:3:1: Executing genrule //plugins/its-jira:its-jira failed: sandbox-exec failed: error executing command /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_zaro0508/e6e07b402568a16bb5c4c2954a1fec35/bazel-sandbox/4e420f04-561f-4e77-a165-0c2ae00ee480-41/sandbox.sb /bin/bash -c ... (remaining 1 argument(s) skipped).
replace META-INF/LICENSE.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
Target //plugins/its-jira:its-jira failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.433s, Critical Path: 3.46s

Patch-set: 27
Reviewer: Gerrit User 1012623 <1012623@173816e5-2b9a-37c3-8a2e-48639d4f1153>